# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.3 on Wed Sep 12 18:13:50 2018
# then modified by nice and beautiful developers
#

import os
import wx
import wx.lib.newevent
import wx.grid
import threading
import time

# Local:
import masso
import logger


DEFAULT_IP_ADDRESS = "192.168.0.22"

WILDCARDS = \
    "GCode files (*.nc,*.gcode)|*.nc;*.gcode|" \
    "All files (*.*)|*.*"


# A new wx event to handle the file transfer progress between multiple threads:
UpdateProgressInfo, EVT_UPDATE_PROGRESS_INFO = wx.lib.newevent.NewEvent()



#  def randomBgColor(widget):
#      return
#      import random
#      minval = 100
#      maxval = 255
#      r = random.randint(minval, maxval)
#      g = random.randint(minval, maxval)
#      b = random.randint(minval, maxval)
#      col = wx.Colour(r, g, b, 255)
#      widget.SetBackgroundColour(col)



class MassoThread(threading.Thread):
    """ Thread which processes file transfers. """

    def __init__(self, ip, filename, lock, verbose):
        threading.Thread.__init__(self)
        self.ip = ip
        self.filename = filename
        self.lock = lock
        self.sender = masso.FileSender(self.ip, self.filename, self.lock, verbose)

    def run(self):
        self.sender.start()



class ProgressThread(threading.Thread):
    """ Thread which regularly retrieves the file transfer progress, and update
        the GUI accordingly.
    """

    def __init__(self, frame, sender, lock):
        threading.Thread.__init__(self)
        self.frame = frame
        self.sender = sender
        self.lock = lock

    def run(self):
        percent = 0
        while percent != 100:
            time.sleep(0.05)
            with self.lock:
                infos = self.sender.progressInfo
                percent = infos.percent
                self.frame.setProgressInfo(infos)


class Frame(wx.Frame):
    """ The main window of the application. """

    def __init__(self, default_ip=None, default_file='', verbose=False):
        if (default_ip == None):
            default_ip = DEFAULT_IP_ADDRESS

        self.verbose = verbose

        # begin wxGlade: Frame.__init__
        wx.Frame.__init__(self, None, wx.ID_ANY, "", style=wx.DEFAULT_FRAME_STYLE)
        self.currentDirectory = os.getcwd()

        # MAIN WINDOW:
        # Will be updated after, these values are useless (see onFrameActivate()):
        self.SetSize((300, 300))

        # MAIN NOTEBOOK:
        self.notebook = wx.Notebook(self, wx.ID_ANY)

        # CONNECT PANEL:
        self.notebook_panel_connect = wx.Panel(self.notebook, wx.ID_ANY)
        self.ip_input = wx.TextCtrl(self.notebook_panel_connect, wx.ID_ANY, default_ip, style=wx.TE_CENTRE)
        self.connect_bt = wx.ToggleButton(self.notebook_panel_connect, wx.ID_ANY, "CONNECT")
        self.select_file_bt = wx.Button(self.notebook_panel_connect, wx.ID_ANY, "SELECT FILE")
        self.send_file_bt = wx.Button(self.notebook_panel_connect, wx.ID_ANY, "SEND")

        # STATUS PANEL:
        self.notebook_panel_status = wx.Panel(self.notebook, wx.ID_ANY)

        # TOOLS PANEL:
        self.notebook_panel_tools = wx.Panel(self.notebook, wx.ID_ANY)
        self.tools_grid_name = wx.grid.Grid(self.notebook_panel_tools, wx.ID_ANY, size=(1, 1))

        self.__set_properties()
        self.__do_layout()

        # EVENTS:
        self.Bind(wx.EVT_TOGGLEBUTTON, self.connect, self.connect_bt)
        self.Bind(wx.EVT_BUTTON, self.onOpenFile, self.select_file_bt)
        self.Bind(wx.EVT_BUTTON, self.send, self.send_file_bt)
        # end wxGlade

        self.progressInfo = None

        # Set the file path initially (empty path):
        self.setFilePath(default_file, update_layout=False)

        # A workaround for the Linux "Awesome" window manager:
        self.firstActivate = True
        self.Bind(wx.EVT_ACTIVATE, self.onFrameActivate)

        self.sendFileThread = None
        self.progressThread = None

        self.Bind(EVT_UPDATE_PROGRESS_INFO, self.onUpdateProgressInfo)


    def __set_properties(self):
        # begin wxGlade: Frame.__set_properties

        # MAIN WINDOW:
        self.SetTitle("Masso Sender")

        # CONNECT PANEL:
        #  self.select_file_bt.SetMinSize((120, 22))
        #  self.send_file_bt.SetMinSize((120, 22))

        # TOOLS PANEL:
        self.tools_grid_name.CreateGrid(2, 2)
        self.tools_grid_name.EnableEditing(0)
        self.tools_grid_name.SetColLabelValue(0, "TOOL NO.")
        self.tools_grid_name.SetColSize(0, 201)
        self.tools_grid_name.SetColLabelValue(1, "TOOL NAME")
        self.tools_grid_name.SetColSize(1, 106)
        self.tools_grid_name.SetRowSize(0, 5)
        self.tools_grid_name.SetRowSize(1, 5)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Frame.__do_layout

        # CONNECT PANEL:
        self.grid_sizer_2 = wx.FlexGridSizer(4, 1, 0, 0)
        #  self.grid_sizer_2.AddGrowableRow(0, 1)
        self.grid_sizer_2.AddGrowableRow(1, 1)
        self.grid_sizer_2.AddGrowableRow(2, 1)
        #  self.grid_sizer_2.AddGrowableRow(3, 1)
        self.grid_sizer_2.AddGrowableCol(0, 1)


        # IP SELECTION SECTION:

        ip_sizer = wx.BoxSizer(wx.VERTICAL)

        # Label 'MASSO IP ADDRESS':
        label_4 = wx.StaticText(self.notebook_panel_connect, wx.ID_ANY, "MASSO IP ADDRESS :", style=wx.ALIGN_CENTER)
        #  label_4.SetMinSize((136, 15))
        label_4.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        ip_sizer.Add(label_4, 0, wx.ALIGN_CENTER | wx.BOTTOM, 5)

        # Text input (ip):
        self.ip_input.SetMinSize((236, 35))
        ip_sizer.Add(self.ip_input, 0, wx.ALIGN_CENTER, 0)

        self.grid_sizer_2.Add(ip_sizer, 0, wx.ALIGN_CENTER | wx.EXPAND | wx.TOP, 10)


        # CONNECT SECTION:

        # Button 'CONNECT':
        self.connect_bt.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Futura Std"))
        self.connect_bt.SetMinSize((150,40))
        self.grid_sizer_2.Add(self.connect_bt, 0, wx.ALIGN_CENTER, 0)


        # FILE SELECTION SECTION:

        file_sizer = wx.BoxSizer(wx.VERTICAL)

        # Button 'SELECT FILE'
        self.select_file_bt.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Futura Std"))
        self.select_file_bt.SetMinSize((180,40))
        file_sizer.Add(self.select_file_bt, 0, wx.ALIGN_CENTER, 0)

        # Text label (file path):
        self.file_path = wx.StaticText(self.notebook_panel_connect, wx.ID_ANY, "", style=wx.ALIGN_CENTER)
        self.file_path.SetMinSize((136, 25))
        self.file_path.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        file_sizer.Add(self.file_path, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.EXPAND, 0)

        self.grid_sizer_2.Add(file_sizer, 0, wx.ALIGN_CENTER, 0)


        # SEND SECTION:

        self.send_sizer = wx.BoxSizer(wx.VERTICAL)

        # Button 'SEND':
        self.send_file_bt.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Futura Std"))
        self.send_file_bt.SetMinSize((120,40))
        self.send_sizer.Add(self.send_file_bt, 0, wx.ALIGN_CENTER, 0)

        # Gauge:
        self.gauge = wx.Gauge(self.notebook_panel_connect, wx.ID_ANY, 100)
        self.gauge.SetMaxSize(wx.Size(8000, 7))
        self.send_sizer.Add(self.gauge, 0, wx.ALIGN_CENTER | wx.EXPAND | wx.TOP, 5)

        # Text label (progress):
        self.progress_label = wx.StaticText(self.notebook_panel_connect, wx.ID_ANY, "", style=wx.ALIGN_CENTER)
        self.progress_label.SetFont(wx.Font(11, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        self.send_sizer.Add(self.progress_label, 0, wx.ALIGN_CENTER | wx.TOP | wx.BOTTOM, 5)

        self.grid_sizer_2.Add(self.send_sizer, 0, wx.ALIGN_CENTER | wx.EXPAND | wx.LEFT | wx.RIGHT, 10)



        self.notebook_panel_connect.SetSizer(self.grid_sizer_2)



        # STATUS PANEL:
        grid_sizer_1 = wx.BoxSizer(wx.VERTICAL)
        label_3 = wx.StaticText(self.notebook_panel_status, wx.ID_ANY, "MACHINE STATUS :", style=wx.ALIGN_CENTER)
        label_3.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        grid_sizer_1.Add(label_3, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        status_input = wx.StaticText(self.notebook_panel_status, wx.ID_ANY, "-", style=wx.ALIGN_CENTER)
        status_input.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        grid_sizer_1.Add(status_input, 0, wx.EXPAND, 0)
        percent_input = wx.StaticText(self.notebook_panel_status, wx.ID_ANY, "-", style=wx.ALIGN_CENTER)
        percent_input.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        grid_sizer_1.Add(percent_input, 0, wx.EXPAND, 0)
        counter_input = wx.StaticText(self.notebook_panel_status, wx.ID_ANY, "-", style=wx.ALIGN_CENTER)
        counter_input.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        grid_sizer_1.Add(counter_input, 0, wx.EXPAND, 0)
        spacer_2 = wx.StaticLine(self.notebook_panel_status, wx.ID_ANY)
        grid_sizer_1.Add(spacer_2, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 0)
        serial_no_input = wx.StaticText(self.notebook_panel_status, wx.ID_ANY, "Serial No : ", style=wx.ALIGN_CENTER)
        serial_no_input.SetMinSize((136, 15))
        serial_no_input.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        grid_sizer_1.Add(serial_no_input, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        core_version_input = wx.StaticText(self.notebook_panel_status, wx.ID_ANY, "Core Version :", style=wx.ALIGN_CENTER)
        core_version_input.SetMinSize((136, 15))
        core_version_input.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        grid_sizer_1.Add(core_version_input, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        software_version_input = wx.StaticText(self.notebook_panel_status, wx.ID_ANY, "Software Version :", style=wx.ALIGN_CENTER)
        software_version_input.SetMinSize((136, 15))
        software_version_input.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.LIGHT, 0, "Futura Std"))
        grid_sizer_1.Add(software_version_input, 0, wx.ALIGN_BOTTOM | wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.notebook_panel_status.SetSizer(grid_sizer_1)

        # TOOLS PANEL:
        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.tools_grid_name, 0, wx.ALIGN_CENTER, 0)
        self.notebook_panel_tools.SetSizer(sizer_4)

        # MAIN NOTEBOOK:
        self.notebook.AddPage(self.notebook_panel_connect, "CONNECT")
        self.notebook.AddPage(self.notebook_panel_status, "STATUS")
        self.notebook.AddPage(self.notebook_panel_tools, "TOOLS")

        # MAIN SIZER:
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.notebook, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade


    def onFrameActivate(self, event):
        """ A workaround for the Linux "Awesome" window manager.  """

        # TODO: the current solution (using a firstActivate prop) is not very good:
        if self.firstActivate:
            self.SetSize((400, 400))
            self.Center()
            self.firstActivate = False


    def onUpdateProgressInfo(self, event):
        """ Update the display in order to show the file transfer progress.  """

        percent = self.progressInfo.percent
        self.progress_label.SetLabel("{}%".format(percent))
        self.gauge.SetValue(percent)
        self.send_sizer.Layout()


    def setFilePath(self, file_path, update_layout=True):
        """ Set a new file path, and update the GUI accordingly. """

        self.inputFilePath = file_path
        self.progressInfo = None
        self.updateFileLabel(update_layout)


    def setProgressInfo(self, info):
        """ Update the file transfer progress informations, and send a signal in order to
            refresh the display.
        """

        self.progressInfo = info
        wx.PostEvent(self, UpdateProgressInfo())


    def updateFileLabel(self, update_layout=True):
        """ Update the `self.file_path` label, depending on the `self.inputFilePath` property.

        Args:
            update_layout: indicates if the layout has to be redrawn
        """

        basename = os.path.basename(self.inputFilePath)
        text = 'File: {}'.format(basename)
        if self.progressInfo != None:
            text += ' - {}%'.format(self.progressInfo.percent)
        self.file_path.SetLabel(text)
        if update_layout:
            self.grid_sizer_2.Layout()


    def connect(self, event):  # wxGlade: Frame.<event_handler>
        print("Event handler 'connect' not implemented!")
        event.Skip()


    def onOpenFile(self, event):
        """ Create and show the Open FileDialog """

        dlg = wx.FileDialog(
            self,
            message = "Choose a file",
            defaultDir = self.currentDirectory,
            defaultFile = "",
            wildcard = WILDCARDS,
            style = wx.FD_OPEN | wx.FD_MULTIPLE | wx.FD_CHANGE_DIR
        )

        if dlg.ShowModal() == wx.ID_OK:
            self.setFilePath(dlg.GetPath())
            dlg.Destroy()

            print("You chose the following file(s):")
            print(self.inputFilePath)


    def send(self, event):
        """ Start a file transfer. """

        if self.sendFileThread and self.sendFileThread.isAlive():
            logger.reset()
            print "Already sending file! Aborting."
            return

        lock = threading.Lock()

        self.sendFileThread = MassoThread(self.ip_input.GetValue(), self.inputFilePath,
                lock, self.verbose)
        self.progressThread = ProgressThread(self, self.sendFileThread.sender, lock)

        self.sendFileThread.start()
        self.progressThread.start()



class MassoSenderApp(wx.App):
    def __init__(self, default_file='', default_ip=DEFAULT_IP_ADDRESS, verbose=False):
        self.defaultIp = default_ip
        self.defaultFile = default_file
        self.verbose = verbose
        wx.App.__init__(self)

    def OnInit(self):
        self.frame = Frame(default_ip=self.defaultIp, default_file=self.defaultFile, verbose=self.verbose)
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

